### ISSUE TITLE
URGENT!!! Update ioBroker repo ... there nuki2 is still referenced and this breaks the repository!!

### ISSUE THREAD

**Issue by Apollon77** [Zefau/ioBroker.nuki-extended#28]
adapter names are not equal: nuki2 !== nuki-extended

Icon of adapter nuki2: https://raw.githubusercontent.com/Zefau/ioBroker.nuki2/master/admin/nuki-logo.png not getable

**Comment by Zefau** [comment]
See https://github.com/ioBroker/ioBroker.repositories/pull/510

**Comment by Apollon77** [comment]
Ok I comment there. Niki needs to be removed then. Such a renaming is very uncommon and produced lots of problems :-(

What is the reason for the rename?

**Comment by Zefau** [comment]
I added the newly published device called Nuki Opener (and the new features introduced in the API).

Due to these changes it is more than a second nuki adapter (nuki2) which is why I renamed it to nuki-extended.

In the pr the URL for Nuki2 is corrected to the valid branch (https://raw.githubusercontent.com/Zefau/ioBroker.nuki-extended/nuki2/io-package.json), so it won't run into errors.

**Comment by Zefau** [comment]
I'm sorry if this caused troubles.

**Comment by Apollon77** [comment]
see comments in Repo issue .. Please really rethink about the rename!!

**Comment by Apollon77** [comment]
Why closed? With "rethink" I also meaned that this one should be renamed back to nuki2

**Comment by Zefau** [comment]
bluefox has added it to the latest repo now and removed nuki2. Renaming this Github Repository now would lead to the same trouble then.

**Comment by Apollon77** [comment]
Ahh ok this was the solution ... did not saw that.kk
