### ISSUE TITLE
Update to iobroker.nuki-extended not displayed in admin adapter

### ISSUE THREAD

**Issue by captaindork** [Zefau/ioBroker.nuki-extended#31]
Hi,
usually in iobroker I install an adapter, and as soon as an updated version is available in the repo, then this is highlighted in the adapter menuitem of the admin page.
Then this Adapter can be updated, just with a click on the update button.

For nuki-extended there are updates, for example from rc6 to rc7, which are not recognized.
It looks as if they are all recogized as Version 2.0.0.
Also normally you can revert to a previous version in the gui in Expert view, but for nuki adapter i can only select 2.0.0.

Probably a versioning like x.y.z (without -rcX) will solve this, could you please Check?

**Comment by Zefau** [comment]
The updates in ioBroker are retrieved from npm (node package manager). In npm, the current version is still `rc.6`, because I have not released the latest rc to it (see https://www.npmjs.com/package/iobroker.nuki-extended). I think this is why `rc.7` (latest version in this Github repository) is not shown within ioBroker.

Regarding the possibility to revert back to a previous version I agree, this might be most likely caused by the versioning.

When all bugs are fixed, v2.0.0 and further versions will follow the "correct" versioning.

Thanks for reporting and popping this up.

**Comment by captaindork** [comment]
![CB51EF64-3969-4D0F-867B-7EC6B2F898B3](https://user-images.githubusercontent.com/28271030/67235592-a800f080-f447-11e9-9b54-e9f52d8104ed.jpeg)
Well also rc5 to rc6 is shown, but its not possible to Update (no Update Button).
Ok Perfect if its fixed for release. The comfort of the admin adapter gets a bit lost when some adapters need to be installed manually even if the update is „listed“.
Nevertheless thanks for a great adapter!!!

**Comment by Zefau** [comment]
I agree with you. I wanted to avoid a high minor version (like 2.0.100) with this versioning, but didn't know it causes troubles.

Thanks for letting me know.
