### ISSUE TITLE
too many callbacks

### ISSUE THREAD

**Issue by arteck** [Zefau/ioBroker.nuki-extended#74]
![grafik](https://user-images.githubusercontent.com/6681528/87527891-0ed8d080-c68d-11ea-8e99-1cf100e4f0d0.png)

**Comment by Zefau** [comment]
Delete one of your callbacks so ioBroker can use one of the three slots.

**Comment by Zefau** [comment]
The current callbacks can be found (and also deleted) via `nuki-extended.0.bridges.<bridgeName>.callbacks`.
There is a maximum of 3 callbacks per bridge. The adapter can't attach a callback, because no free slot is given, which is why a warning is shown in the log.

Delete one of the existing callbacks and restart the adapter.

If the warning persists, please let me know the URLs that are attached already as well as the log in `debug` mode.
